/**
 * Aethelgard PDF Studio license key generation.
 *
 * Standalone product key, separate from Aethelgard's main licence (`AETHG-…`).
 * Aethelgard licence holders get PDF Studio for free using their existing
 * Aethelgard key — those are validated by the PDF Studio app via the existing
 * Aethelgard verifier. Standalone PDF Studio buyers receive a `PDFST-…` key
 * minted here.
 *
 * Key format: PDFST-XXXXXX-XXXXXX-XXXXXX-XXXXXX
 *   24 Crockford Base32 chars = 120 bits = 15 bytes
 *
 * Byte layout (parity with Aethelgard's keygen):
 *   [0]    version(4 bits) | tier(4 bits)  — version is always 1
 *   [1-2]  expiry_months u16 BE (months since 2026-01-01)
 *   [3-6]  customer_id u32 BE
 *   [7-14] first 8 bytes of HMAC-SHA256(bytes[0..7] || "PDFST", masterSecret)
 *
 * The product code "PDFST" is appended to the HMAC input so an Aethelgard key
 * cannot be re-prefixed and forged as a PDF Studio key — the HMACs differ even
 * with identical bytes 0–6.
 *
 * Tier values (room to grow):
 *   0 = standalone (single user, single machine)
 *
 * No lifetime tier — PDF Studio is annual subscription only.
 *
 * Must stay in perfect sync with the PDF Studio app's verifier
 * (apps/studio/src-tauri/src/license.rs — created in Phase 6.2).
 */

export type PdfStudioTier = 'standalone';

const TIER_BYTE: Record<PdfStudioTier, number> = {
    standalone: 0,
};

const ALPHABET = '0123456789ABCDEFGHJKMNPQRSTVWXYZ';
const EPOCH    = new Date(Date.UTC(2026, 0, 1));
const PRODUCT_CODE = 'PDFST';

/** Strip prefix and dashes; uppercase. Mirrors the verifier's normalise logic. */
export function normalizePdfStudioKey(raw: string): string {
    return raw.replace(/[^0-9A-Za-z]/g, '').toUpperCase().replace(/^PDFST/, '');
}

/** SHA-256 of the normalised key body. Used as the revocation registry index. */
export async function hashPdfStudioKey(raw: string): Promise<string> {
    const data = new TextEncoder().encode(normalizePdfStudioKey(raw));
    const buf  = await crypto.subtle.digest('SHA-256', data);
    return Array.from(new Uint8Array(buf)).map(b => b.toString(16).padStart(2, '0')).join('');
}

/**
 * Generate a formatted PDF Studio license key.
 *
 * @param tier         Feature tier to encode (currently only 'standalone').
 * @param customerId   u32 customer identifier (random, generated by caller).
 * @param expiryDate   Annual expiry date — required (no lifetime keys).
 * @param masterSecret Shared HMAC secret (AETHELGARD_LICENSE_SECRET).
 */
export async function generatePdfStudioKey(
    tier: PdfStudioTier,
    customerId: number,
    expiryDate: Date,
    masterSecret: string,
): Promise<string> {
    if (!expiryDate) {
        throw new Error('PDF Studio keys require an expiry date — no lifetime tier.');
    }

    const buf = new Uint8Array(15);
    buf[0] = (1 << 4) | TIER_BYTE[tier];

    const months = dateToMonths(expiryDate);
    buf[1] = (months >> 8) & 0xff;
    buf[2] =  months       & 0xff;

    buf[3] = (customerId >>> 24) & 0xff;
    buf[4] = (customerId >>> 16) & 0xff;
    buf[5] = (customerId >>>  8) & 0xff;
    buf[6] =  customerId         & 0xff;

    const hmac = await computeProductHmac(buf.slice(0, 7), masterSecret);
    buf.set(hmac.slice(0, 8), 7);

    const encoded = encodeBase32(buf);
    return `PDFST-${encoded.slice(0, 6)}-${encoded.slice(6, 12)}-${encoded.slice(12, 18)}-${encoded.slice(18, 24)}`;
}

/** Generate a cryptographically random u32 customer ID. */
export function randomCustomerId(): number {
    const buf = new Uint8Array(4);
    crypto.getRandomValues(buf);
    return ((buf[0] << 24) | (buf[1] << 16) | (buf[2] << 8) | buf[3]) >>> 0;
}

/** 13 months from now: 1 year + 1 month grace. Mirrors Aethelgard's annual policy. */
export function annualExpiry(): Date {
    const d = new Date();
    d.setUTCMonth(d.getUTCMonth() + 13);
    return d;
}

// ── Private helpers ───────────────────────────────────────────────────────────

function dateToMonths(d: Date): number {
    const months =
        (d.getUTCFullYear() - EPOCH.getUTCFullYear()) * 12 +
        (d.getUTCMonth()    - EPOCH.getUTCMonth());
    return Math.max(0, Math.min(0xfffe, months));
}

/** HMAC-SHA256 over `bytes || PRODUCT_CODE` — binds the signature to the product. */
async function computeProductHmac(bytes: Uint8Array, secret: string): Promise<Uint8Array> {
    const enc = new TextEncoder();
    const productBytes = enc.encode(PRODUCT_CODE);
    const data = new Uint8Array(bytes.length + productBytes.length);
    data.set(bytes, 0);
    data.set(productBytes, bytes.length);

    const key = await crypto.subtle.importKey(
        'raw',
        enc.encode(secret),
        { name: 'HMAC', hash: 'SHA-256' },
        false,
        ['sign'],
    );
    const sig = await crypto.subtle.sign('HMAC', key, data);
    return new Uint8Array(sig);
}

function encodeBase32(bytes: Uint8Array): string {
    let acc = 0n;
    for (const b of bytes) acc = (acc << 8n) | BigInt(b);
    let out = '';
    for (let i = 23; i >= 0; i--) {
        const idx = Number((acc >> BigInt(i * 5)) & 0x1fn);
        out += ALPHABET[idx];
    }
    return out;
}

/**
 * Verify a PDF Studio key — used for self-tests and (future) server-side
 * revocation checks. The PDF Studio app does its own offline verification in
 * Rust; this is the JS counterpart for parity testing.
 *
 * Returns the decoded payload on success, or throws.
 */
export async function verifyPdfStudioKey(
    raw: string,
    masterSecret: string,
): Promise<{ tier: PdfStudioTier; customerId: number; expiryDate: Date | null }> {
    const body = normalizePdfStudioKey(raw);
    if (body.length !== 24) throw new Error('Key must be 24 Crockford Base32 chars.');
    if (!raw.replace(/[^0-9A-Za-z]/gi, '').toUpperCase().startsWith('PDFST')) {
        throw new Error('Key prefix must be PDFST.');
    }

    const bytes = decodeBase32(body);

    const versionAndTier = bytes[0]!;
    if ((versionAndTier >> 4) !== 1) throw new Error('Unsupported version.');
    const tierByte = versionAndTier & 0x0f;
    const tier = (Object.entries(TIER_BYTE).find(([, v]) => v === tierByte)?.[0]) as
        | PdfStudioTier
        | undefined;
    if (!tier) throw new Error(`Unknown tier byte: ${tierByte}`);

    const months = (bytes[1]! << 8) | bytes[2]!;
    if (months === 0xffff) throw new Error('Lifetime keys are not valid for PDF Studio.');
    const expiryDate = monthsToDate(months);

    const customerId =
        ((bytes[3]! << 24) | (bytes[4]! << 16) | (bytes[5]! << 8) | bytes[6]!) >>> 0;

    const expectedHmac = await computeProductHmac(bytes.slice(0, 7), masterSecret);
    for (let i = 0; i < 8; i++) {
        if (expectedHmac[i] !== bytes[7 + i]) throw new Error('HMAC mismatch — invalid or forged key.');
    }

    return { tier, customerId, expiryDate };
}

function monthsToDate(months: number): Date {
    const d = new Date(EPOCH);
    d.setUTCMonth(d.getUTCMonth() + months);
    return d;
}

function decodeBase32(s: string): Uint8Array {
    let acc = 0n;
    for (const c of s) {
        const idx = ALPHABET.indexOf(c);
        if (idx === -1) throw new Error(`Invalid Crockford Base32 char: ${c}`);
        acc = (acc << 5n) | BigInt(idx);
    }
    const out = new Uint8Array(15);
    for (let i = 14; i >= 0; i--) {
        out[i] = Number(acc & 0xffn);
        acc >>= 8n;
    }
    return out;
}
