/**
 * Aethelgard license key generation.
 *
 * Must stay in perfect sync with src-tauri/src/license.rs.
 *
 * Key format: AETHG-XXXXXX-XXXXXX-XXXXXX-XXXXXX
 *   24 Crockford Base32 chars = 120 bits = 15 bytes
 *
 * Byte layout:
 *   [0]    version(4 bits) | tier(4 bits)  — version is always 1
 *   [1-2]  expiry_months u16 BE (months since 2026-01-01; 0xFFFF = lifetime)
 *   [3-6]  customer_id u32 BE
 *   [7-14] first 8 bytes of HMAC-SHA256(bytes[0..7], masterSecret)
 *
 * Tier values: 0=basic, 1=standard, 2=advanced
 */

export type Tier = 'basic' | 'standard' | 'advanced';

const TIER_BYTE: Record<Tier, number> = {
    basic:    0,
    standard: 1,
    advanced: 2,
};

/** Crockford Base32 alphabet — no ambiguous 0/O/I/L. */
const ALPHABET = '0123456789ABCDEFGHJKMNPQRSTVWXYZ';

/** Months are counted from 2026-01-01 (same epoch as Rust). */
const EPOCH = new Date(Date.UTC(2026, 0, 1)); // 2026-01-01 UTC

export const LIFETIME: number = 0xFFFF;

// ── Key hashing (for revocation registry) ────────────────────────────────────

/**
 * Normalise a raw key string to its 24-character Crockford Base32 body.
 * Strips prefix, dashes, whitespace; uppercases. Mirrors Rust's normalise logic.
 */
export function normalizeKey(raw: string): string {
    return raw.replace(/[^0-9A-Za-z]/g, '').toUpperCase().replace(/^AETHG/, '');
}

/**
 * SHA-256 digest of the normalised key body, returned as a lowercase hex string.
 * Used as the storage key in the revocation registry — never store the raw key.
 */
export async function hashKey(raw: string): Promise<string> {
    const data = new TextEncoder().encode(normalizeKey(raw));
    const buf  = await crypto.subtle.digest('SHA-256', data);
    return Array.from(new Uint8Array(buf)).map(b => b.toString(16).padStart(2, '0')).join('');
}

// ── Public API ────────────────────────────────────────────────────────────────

/**
 * Generate a formatted license key.
 *
 * @param tier         Feature tier to encode.
 * @param customerId   u32 customer identifier (random, generated by caller).
 * @param expiryDate   Expiry date, or null for a lifetime key.
 * @param masterSecret The shared HMAC secret (must match AETHELGARD_LICENSE_SECRET in binary).
 */
export async function generateKey(
    tier: Tier,
    customerId: number,
    expiryDate: Date | null,
    masterSecret: string,
): Promise<string> {
    const buf = new Uint8Array(15);

    buf[0] = (1 << 4) | TIER_BYTE[tier];

    const months = expiryDate === null ? LIFETIME : dateToMonths(expiryDate);
    buf[1] = (months >> 8) & 0xff;
    buf[2] =  months       & 0xff;

    // customer_id as u32 big-endian
    buf[3] = (customerId >>> 24) & 0xff;
    buf[4] = (customerId >>> 16) & 0xff;
    buf[5] = (customerId >>>  8) & 0xff;
    buf[6] =  customerId         & 0xff;

    const hmac = await computeHmac(buf.buffer.slice(0, 7), masterSecret);
    buf.set(hmac.slice(0, 8), 7);

    const encoded = encodeBase32(buf);
    return `AETHG-${encoded.slice(0, 6)}-${encoded.slice(6, 12)}-${encoded.slice(12, 18)}-${encoded.slice(18, 24)}`;
}

/** Generate a cryptographically random u32 customer ID. */
export function randomCustomerId(): number {
    const buf = new Uint8Array(4);
    crypto.getRandomValues(buf);
    return ((buf[0] << 24) | (buf[1] << 16) | (buf[2] << 8) | buf[3]) >>> 0;
}

/**
 * Compute the expiry date for an annual subscription: 13 months from now
 * (one month grace period so customers renewing a day late don't lose access).
 */
export function annualExpiry(): Date {
    const d = new Date();
    d.setUTCMonth(d.getUTCMonth() + 13);
    return d;
}

/** Lifetime key: pass null as expiryDate to generateKey. */
export const lifetimeExpiry = null;

// ── Private helpers ───────────────────────────────────────────────────────────

/** Convert a Date to months-since-2026-01-01 (clamped to u16 range). */
function dateToMonths(d: Date): number {
    const epochYear  = EPOCH.getUTCFullYear();
    const epochMonth = EPOCH.getUTCMonth();
    const months =
        (d.getUTCFullYear() - epochYear) * 12 +
        (d.getUTCMonth() - epochMonth);
    return Math.max(0, Math.min(0xfffe, months));
}

/** HMAC-SHA256 using the Web Crypto API (available in Vercel Edge + Node ≥18). */
async function computeHmac(data: ArrayBuffer, secret: string): Promise<Uint8Array> {
    const enc = new TextEncoder();
    const key = await crypto.subtle.importKey(
        'raw',
        enc.encode(secret),
        { name: 'HMAC', hash: 'SHA-256' },
        false,
        ['sign'],
    );
    const sig = await crypto.subtle.sign('HMAC', key, data);
    return new Uint8Array(sig);
}

/** Encode 15 bytes as 24 Crockford Base32 characters (big-endian). */
function encodeBase32(bytes: Uint8Array): string {
    // Pack 15 bytes (120 bits) into a BigInt, then read 24 × 5-bit groups.
    let acc = 0n;
    for (const b of bytes) acc = (acc << 8n) | BigInt(b);

    let out = '';
    for (let i = 23; i >= 0; i--) {
        const idx = Number((acc >> BigInt(i * 5)) & 0x1fn);
        out += ALPHABET[idx];
    }
    return out;
}
